In [77]:
import pandas as pd
import numpy as np

# read some existing data from pandas
df = pd.read_csv('../communities_cleaned.csv')
df

population  householdsize  racepctblack  racePctWhite  racePctAsian   
0           0.19           0.33          0.02          0.90          0.12  \
1           0.00           0.16          0.12          0.74          0.45   
2           0.00           0.42          0.49          0.56          0.17   
3           0.04           0.77          1.00          0.08          0.12   
4           0.01           0.55          0.02          0.95          0.09   
...          ...            ...           ...           ...           ...   
1989        0.01           0.40          0.10          0.87          0.12   
1990        0.05           0.96          0.46          0.28          0.83   
1991        0.16           0.37          0.25          0.69          0.04   
1992        0.08           0.51          0.06          0.87          0.22   
1993        0.20           0.78          0.14          0.46          0.24   

      racePctHisp  agePct12t21  agePct12t29  agePct16t24  agePct65up  ...   
0            0.17         0.34         0.47         0.29        0.32  ...  \
1            0.07         0.26         0.59         0.35        0.27  ...   
2            0.04         0.39         0.47         0.28        0.32  ...   
3            0.10         0.51         0.50         0.34        0.21  ...   
4            0.05         0.38         0.38         0.23        0.36  ...   
...           ...          ...          ...          ...         ...  ...   
1989         0.16         0.43         0.51         0.35        0.30  ...   
1990         0.32         0.69         0.86         0.73        0.14  ...   
1991         0.25         0.35         0.50         0.31        0.54  ...   
1992         0.10         0.58         0.74         0.63        0.41  ...   
1993         0.77         0.50         0.62         0.40        0.17  ...   

      PctForeignBorn  PctBornSameState  PctSameHouse85  PctSameCity85   
0               0.12              0.42            0.50           0.51  \
1               0.21              0.50            0.34           0.60   
2               0.14              0.49            0.54           0.67   
3               0.19              0.30            0.73           0.64   
4               0.11              0.72            0.64           0.61   
...              ...               ...             ...            ...   
1989            0.22              0.28            0.34           0.48   
1990            0.53              0.25            0.17           0.10   
1991            0.25              0.68            0.61           0.79   
1992            0.45              0.64            0.54           0.59   
1993            0.68              0.50            0.34           0.35   

      PctSameState85  LandArea  PopDens  PctUsePubTrans  LemasPctOfficDrugUn   
0               0.64      0.12     0.26            0.20                 0.32  \
1               0.52      0.02     0.12            0.45                 0.00   
2               0.56      0.01     0.21            0.02                 0.00   
3               0.65      0.02     0.39            0.28                 0.00   
4               0.53      0.04     0.09            0.02                 0.00   
...              ...       ...      ...             ...                  ...   
1989            0.39      0.01     0.28            0.05                 0.00   
1990            0.00      0.02     0.37            0.20                 0.00   
1991            0.76      0.08     0.32            0.18                 0.91   
1992            0.52      0.03     0.38            0.33                 0.22   
1993            0.68      0.11     0.30            0.05                 1.00   

      ViolentCrimesPerPop  
0                    0.20  
1                    0.67  
2                    0.43  
3                    0.12  
4                    0.03  
...                   ...  
1989                 0.09  
1990                 0.45  
1991                 0.23  
1992                 0.19  
1993      

In [82]:
df.columns[:5][[True, True, False, True, False]]

Index(['population', 'householdsize', 'racePctWhite'], dtype='object')

In [62]:
df0 = df.iloc[:, 0:4]
df0

population  householdsize  racepctblack  racePctWhite
0           0.19           0.33          0.02          0.90
1           0.00           0.16          0.12          0.74
2           0.00           0.42          0.49          0.56
3           0.04           0.77          1.00          0.08
4           0.01           0.55          0.02          0.95
...          ...            ...           ...           ...
1989        0.01           0.40          0.10          0.87
1990        0.05           0.96          0.46          0.28
1991        0.16           0.37          0.25          0.69
1992        0.08           0.51          0.06          0.87
1993        0.20           0.78          0.14          0.46

[1994 rows x 4 columns]

In [71]:
df0.to_numpy().

array([[0.19, 0.33, 0.02, 0.9 ],
       [0.  , 0.16, 0.12, 0.74],
       [0.  , 0.42, 0.49, 0.56],
       ...,
       [0.16, 0.37, 0.25, 0.69],
       [0.08, 0.51, 0.06, 0.87],
       [0.2 , 0.78, 0.14, 0.46]])

In [7]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

1994

In [9]:
from sklearn.datasets import load_digits
from sklearn.decomposition import FactorAnalysis

X, _ = load_digits(return_X_y=True)
transformer = FactorAnalysis(n_components=7, random_state=0)
X_transformed = transformer.fit_transform(X)
X_transformed.shape

(1797, 7)

In [13]:
transformer.components_.shape

(7, 64)

In [30]:
np.cov(X, rowvar=False).shape

(64, 64)

In [35]:
from sklearn.decomposition import PCA

pca = PCA()
pca.fit(X)
pca.components_.shape

(64, 64)

In [39]:
X[:90].shape

(90, 64)

In [44]:
# Generate a random m*n matrix
m, n = 6, 12
X = np.random.randn(m, n)
from scipy import linalg
N = linalg.null_space(X)

In [53]:
X = np.random.randn(12, 6)

N = linalg.null_space(X.T)
N.T @ X

array([[ 1.47626855e-16,  1.72292397e-16,  1.66209205e-16,
         4.07095661e-16, -1.78708754e-16,  8.50513333e-17],
       [ 9.38552778e-17, -2.69962839e-16, -1.46061627e-16,
        -2.03946536e-16, -1.48802238e-16, -1.85470751e-16],
       [ 4.08237227e-16,  1.00929050e-16, -4.49942362e-18,
        -4.10589797e-16,  2.75844948e-16,  1.26881535e-17],
       [-3.30828928e-19, -2.29891445e-16, -1.56134502e-16,
        -8.56327330e-17, -1.28900105e-16,  3.14485128e-17],
       [ 4.83415076e-17, -3.75833978e-17, -4.22673262e-16,
         3.26685671e-16, -2.32596531e-16,  3.07766812e-16],
       [ 5.69568248e-17,  4.66520848e-16, -1.34088806e-16,
         4.93704307e-16,  2.22665989e-16, -3.85244950e-17]])

In [66]:
from sklearn.datasets import make_friedman1
from sklearn.feature_selection import RFECV
from sklearn.svm import SVR
X, y = make_friedman1(n_samples=50, n_features=10, random_state=0)
estimator = SVR(kernel="linear")
selector = RFECV(estimator, step=1, cv=5)
selector = selector.fit(X, y)
selector.support_

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])